### ISSUE TITLE
Write tweets to file

### ISSUE THREAD

**Issue by ghost** [Rickecr/PyTwitter#9]
### Write tweets to file

Allow the user to be able to record the tweets in a json / csv file. By one of two methods:

1. Pass the list of tweets (which are searched by the library).
2. Pass a list of ids of the tweets to be saved.

**Mandatory:** Use the functions that already exist in cases where it is possible. Example:

1. Use the `show` and/or `show_lookup` function.

**Comment by lucascz37** [comment]
Can i contribute to this issue?

**Comment by ghost** [comment]
Okay, I'll put you in charge, any questions just talk.

**Comment by ghost** [comment]
We had a conversation about the CSV file and decided to choose just a few fields:

```text
created_at
id_str
full_text
entities -> hashtags
metadata -> iso_language_code
user -> id_str, screen_name, location
retweet_count
favorite_count
coordinates
```

Later on we can put the user to pass the desired fields.
